// Guía de movimientos (panel de ayuda).
// --- guía de movimientos ---
const G=[
['Las 6 caras','Cada letra es una cara. Sin símbolo gira 90° en el sentido de las agujas del reloj mirando esa cara de frente. Sostén el cubo con amarillo arriba y verde al frente, como en la app.',[['R','Derecha (Right)'],['L','Izquierda (Left)'],['U','Arriba (Up)'],['D','Abajo (Down)'],['F','Frente (Front)'],['B','Atrás (Back)']]],
['Modificadores','Van justo después de la letra.',[["R'",'Prima: 90° en sentido contrario (antihorario)'],['R2','Media vuelta (180°); el sentido da igual'],["R2'",'Igual que R2; algunos algoritmos lo escriben así']]],
['Dos capas a la vez (movimientos anchos)','Letra minúscula, o la mayúscula con w: la cara y la capa del medio pegada a ella giran juntas, en el sentido de esa cara. La app entiende ambas formas.',[['r','Derecha + capa del medio (también Rw)'],['l','Izquierda + capa del medio (Lw)'],['u','Arriba + capa del medio (Uw)'],['d','Abajo + capa del medio (Dw)'],['f','Frente + capa del medio (Fw)'],['b','Atrás + capa del medio (Bw)'],["r'","Ancho en sentido contrario (Rw')"]]],
['Capas del medio','Gira solo la capa central, la que no tiene cara propia. Cada una sigue el sentido de una cara.',[['M','Entre L y R. Gira como L: la columna central del frente baja'],['E','Entre U y D. Gira como D: la fila central del frente va a la derecha'],['S','Entre F y B. Gira como F: horario mirando de frente'],["M'",'M al revés: la columna central del frente sube'],['M2','Media vuelta de M; aparece en los PLL H, Ua, Ub y Z']]],
['Rotaciones de todo el cubo','No cambian el estado, solo cómo sostienes el cubo. x gira como R, y como U y z como F.',[['x','Como R: el frente pasa a arriba'],['y','Como U: el frente pasa a la izquierda'],['z','Como F: arriba pasa a la derecha'],["y'",'y al revés: el frente pasa a la derecha'],['y2','Media vuelta del cubo sobre el eje vertical']]],
['Escritura','Los movimientos se separan con espacios.',[["(R U R' U')3",'Los paréntesis agrupan y el número de después repite el grupo (la app lo expande)']]]];
$('gbody').innerHTML=G.map(([t,d,r])=>`<h3>${t}</h3><div class="hint">${d}</div><div class="gd">${r.map(([m,x])=>`<button class="b" data-g="${esc(m)}">${esc(m)}</button><span>${esc(x)}</span>`).join('')}</div>`).join('');
$('guide').onclick=async e=>{const b=e.target.closest('[data-g]');if(!b)return;const prev=$('cs').checked;$('cs').checked=false;cur=null;preset('solved');$('alg').value=b.dataset.g;load();await reset();$('cs').checked=prev;render();scrollTo({top:0,behavior:'smooth'});setTimeout(play,350)};
